### PR TITLE
fix mobile chat on android (and iphone chrome)

### PR DESCRIPTION
**Pull request by timothyclemansinsea**
You currently can't type messages into the main chatrooms in SMC on mobile chrome (on iOS / Android).  It works fie on mobile safari.

### CODE REVIEW

**Comment by timothyclemansinsea** [comment]
I tried to do a more complicated PR where autofocus is set based on status. However onClick does not fire on mobile, see https://github.com/react-bootstrap/react-bootstrap/issues/2193

**Comment by williamstein** [comment]
Thanks!!

**Comment by williamstein** [comment]
This definitely does not fix anything for iPhone Chrome.  No idea if it fixes Android Chrome or not -- i can't test.  But it looks harmless.

**Comment by williamstein** [comment]
Definitely doesn't fix: https://github.com/sagemathinc/smc/issues/867

**Pull request merged**
