### PR TITLE
Staging/improvements/chat user distinction

### PR DESCRIPTION
**Pull request by johnjeng**
Flips the display of your chat messages vs. other people's and also marks your chat a blue color.

### CODE REVIEW

**Comment by haraldschilly** [comment]
This also pulls in a lot of other random stuff. Which files do actually contain changes? ... Or maybe the pull request target is the wrong one.

**Comment by johnjeng** [comment]
Oh dear, hello, yes it does. Just the very last change.

**Comment by williamstein** [comment]
Please make a new clean fork from master and new pull request.

**Comment by haraldschilly** [comment]
I could try to cherry pick just your commit and apply against master, but then you have to promise to reset your branch pointers to be in sync with upstream ;-)

**Comment by johnjeng** [comment]
I'll just make a clean fork


On Wed, Nov 18, 2015 at 11:26 PM, Harald Schilly <notifications@github.com>
wrote:

> I could try to cherry pick just your commit and apply against master, but
> then you have to promise to reset your branch pointers to be in sync with
> upstream ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/pull/265#issuecomment-157975644>.
>



-- 
John Jeng

**Pull request closed without merging**
