### PR TITLE
Issues/34

### PR DESCRIPTION
**Pull request by johnjeng**
Added ability to search for emails wrapped in angle brackets.
https://github.com/sagemathinc/smc/issues/34

Undocumented (bug/feature):
```
<correct@email.com>garbageStuff
```
becomes
```
correct@email.com
```
even though having things at the beginning doesn't work ie.
```
garbage<incorrect@email.com>
```
will be understood exactly as is and result in an invalid email by RFC822. This is because emails such as 
```
begin"\<weirdness"email"<>"@odd.provider.com
```
are actually valid.

### CODE REVIEW

**Comment by williamstein** [comment]
John,  Can you write some tests for this function and add them here: src/smc-util/test/misc-test.coffee   ?
It should be pretty obvious how to write more tests by looking at what is in that file. 
You can run the tests by typing `npm run test` in the smc-util directory

**Comment by johnjeng** [comment]
Yup, certainly.

**Comment by williamstein** [comment]
Ping.  It would be good to have this in and live before classes start next week.

**Comment by johnjeng** [comment]
Updated the unit test to be on par with current testing style.

Please tell me if more or something different would be preferred.

**Comment by williamstein** [comment]
> Edit: We don't have any mutation testing right?

What is "mutation testing"?

**Comment by williamstein** [comment]
Good job -- I like this; it's now live!

**Pull request merged**
