### PR TITLE
move sign out buttons to top

### PR DESCRIPTION
**Pull request by timothyclemansinsea**
For #977 

image

### CODE REVIEW

**Comment by williamstein** [comment]
Put a screenshot...

**Comment by williamstein** [comment]
Thanks for the screen shot.  Your buttons on the upper right push the entire account settings tabs and page down a full button height, which looks weird.    What about not pushing down?  

Also, screenshot when the screen is skinny...

**Comment by timothyclemansinsea** [comment]
@williamstein I was not able to get the buttons on the same row as the tabs. So I put them in the right column at the top. Now I got to figure out how to make them appear at top when in small screen mode.

**Comment by williamstein** [comment]
> Now I got to figure out how to make them appear at top when in small screen mode.

@timothyclemansinsea  -- You left this for five days...?

**Comment by timothyclemansinsea** [comment]
I dont have a clue how to know if in single column mode. Best i know of is
is_mobile

**Comment by johnjeng** [comment]
This breaks the design pattern for the page so I won't okay it. An alternative is to make a sign out button in the top nav which gives you an option to sign out everywhere or not when you click on it.

**Comment by timothyclemansinsea** [comment]
@williamstein any thoughts on putting sign out in the topbar?

**Comment by williamstein** [comment]
> any thoughts on putting sign out in the topbar?

No, because most people never have to click that button, and it'll just be sitting there wasting space all the time.  There should never be anything on the screen all the time that most people won't derive regular value from.   Look at your top bar right now.  Nothing there is redundant, and I bet you look at and use everything there.

**Comment by williamstein** [comment]
Also, no major websites put sign out buttons at the top visible level, that I know of.

**Comment by timothyclemansinsea** [comment]
OK then I guess I should close this PR then.

**Comment by williamstein** [comment]
Where are the sign out buttons for Google, Facebook, and a few other sites?  The problem still stands -- people sometimes can't find the buttons.

**Comment by timothyclemansinsea** [comment]
Google's sign out is on a dropdown. Facebook's sign out is pretty hidden in
a dropdown. Github's sign out is in a dropdown. Twitter's sign out is in a
dropdown.

**Comment by williamstein** [comment]
> ... is in a dropdown...

Maybe we should have a dropdown?

**Comment by johnjeng** [comment]
Maybe we should have a dropdown on our `Account` button?

**Comment by williamstein** [comment]
@timothyclemansinsea -- thanks for investigating; @johnjeng  -- sounds good to me!

**Comment by timothyclemansinsea** [comment]
Closing because it would take me about an hour or more to fix and this is not a M-high issue.

**Pull request closed without merging**
