### PR TITLE
sagews/jupyter: removing conv.convert from jupyter kernel initialization.

### PR DESCRIPTION
**Pull request by haraldschilly**
makes no sense (?) and if at all, it should be called with full=False. issue #959

test with the example given in the #959 ticket

### CODE REVIEW

**Comment by haraldschilly** [comment]
@DrXyzzy please take a look at this! that one line I removed is probably just some leftover and since there is "full=False" for each cell, that issue doesn't happen in reality.

**Comment by DrXyzzy** [comment]
The change causes many tests in `src/smc_sagews/smc_sagews/tests/test_sagews_modes.py` to fail. I think it relates to initial DOCTYPE. Doing a few more tests.

**Comment by haraldschilly** [comment]
Hmm, good argument regarding the tests. The point for me is, that inserting this whole html document just for an empty string makes no sense to me. It has no impact on the other html and ansi-ascii snippets inserted later.

**Comment by DrXyzzy** [comment]
Looks good in all my automated and (modified) tests. I will update the pytest suite so all tests pass as soon as this change propagates.

**Comment by haraldschilly** [comment]
ok, great! thank you!

**Comment by DrXyzzy** [comment]
The one-line code change here is included in my PR #1082

**Comment by haraldschilly** [comment]
closing, is part of #1082

**Pull request closed without merging**
