### PR TITLE
Navbar details

### PR DESCRIPTION
**Pull request by cloutier**
The icon to contract the navbar depicted the "extend" action, and vice-versa. 

I also made the bell icon the same size as the other icons. I think they are maybe a few pixels too small and I should all make them bigger. What do you think?

### CODE REVIEW

**Comment by williamstein** [comment]
I merged this.  The bell being the "same size" unfortunately looks very small compared to the other icons, and doesn't fit the red notification number that appears when there are unseen chats.   I kept the compress/expand change.   

Active development right now is in the rethinkdb branch, which is a massive rewrite to use rethinkdb on the backend and react.js on the frontend (about 50% there with react now).  You can try it live right now in SMC here: https://web0.sagemath.com/   (ignore the security warning).  You'll see it has your expand/compress change, etc. 

If you want to get more seriously involved in helping with SMC, let me know.    I even have a virtualbox image right now, but running IPython/sage/latex doesn't fully work in it yet.  But for basic UI stuff, it's fine, and you can modify code and see the changes.   That said, we mostly develop online via a project using some self-contained VM's.

**Comment by cloutier** [comment]
I'd love to get involved some more. What's the best way for you to share the VM? 

I think I'm going to do mostly UI stuff and translations (my mothertongue is French), but I'm also going to look into the backend itself a liitle bit. I do not have network access in my projects though.

**Comment by williamstein** [comment]
1. I will upload the image from campus today and send you a link.   For translations and UI, it will be fine, and I'll fix the remaining issues within the next 3 weeks (I need to for a workshop on Aug 21).

2. Our plan for translation is to use http://formatjs.io/react/.  Can you learn about that library?    We are actively rewriting everything in React.js (from jquery+html), and pretty much any code in SMC that isn't in react will be completely rewritten from scratch ASAP.  We got about half way through in the last month...

3. I do not have network access in my projects though. -- Email links to projects to help@sagemath.com, and point out that you're a contributor to SMC, and we'll give you network access on your projects.

**Comment by williamstein** [comment]
By the way, if you could setup the structure for doing UI translation for the react part of SageMathCloud, it would be easy to get people do translate to Russian and a few other languages -- there's many volunteers, due to the popularity of Sage.

**Comment by cloutier** [comment]
I am going to look into this library.

How are you planning to organise the translation efforts? I worked a little bit on ownCloud and they used [Transifex](https://www.transifex.com/). It may be easier for non-technical users than sending pathches to the github project and also more scalable. It is free for open-source projets, but the plateform is not libre.

**Comment by williamstein** [comment]
> How are you planning to organise the translation efforts? 

I don't know.  It depends on how the actual transitions will be structured using react-intl.  Your suggestion to use Transifex seems very good to me.  I'm fine with it not being libre.

**Comment by cloutier** [comment]
Great! I am going to explore how this can all fit together in the react branch. 

You can send me the link to download the VM at vincent1cloutier (at) gmail.com.

**Comment by williamstein** [comment]
You can find the VM here:

   http://wstein.org/smc/vm/

This is my first attempt ever to distribute a VM of SageMathCloud, so things might not go perfectly smoothly.

**Comment by cloutier** [comment]
I am stuck on [the login screen](http://ipfs.pics/QmRBtLQ9Ff2q5WBXSSg9YrcPhDL7sHetPLFRioT5c1iKgp). 

I also had to disable one of the network adapter to start it, as my machine is different than yours, to make it start. I kept the standard NAT. I added a port forwarding, but it doesn't connect, though it might be normal if I am not logged in. I don't know if I need the right hostname, I tried localhost:880 (80 is used for something else).

It might be completely unrelated, but I disabled usb 2.0 because my virtualbox didn't have the proper extension. Disabling that should help making it more portable if it is not needed.

**Comment by williamstein** [comment]
On Thu, Aug 6, 2015 at 8:03 PM, Vincent Cloutier <notifications@github.com>
wrote:

> I am stuck on the login screen
> <http://ipfs.pics/QmRBtLQ9Ff2q5WBXSSg9YrcPhDL7sHetPLFRioT5c1iKgp>.
>

Does a login of salvus and password of salvus not work?

Once in, type /sbin/ifconfig




> I also had to disable one of the network adapter to start it, as my
> machine is different than yours, to make it start. I kept the standard NAT.
> I added a port forwarding, but it doesn't connect, though it might be
> normal if I am not logged in. I don't know if I need the right hostname, I
> tried localhost:880 (80 is used for something else).
>

NAT lets the VM connect to the outside world.  The other adapter, "Host
only adapter, vboxnet0" (say) is the important one though, since it lets
you connect to the virtual machine from your desktop computer.

http://askubuntu.com/questions/293816/in-virtualbox-how-do-i-set-up-host-only-virtual-machines-that-can-access-the-in

If this is too painful, there are alternatives, e.g., a dedicated vm on
google compute engine just for you to do development...


> It might be completely unrelated, but I disabled usb 2.0 because my
> virtualbox didn't have the proper extension. Disabling that should help
> making it more portable if it is not needed.
>

usb 2.0 probably isn't relevant.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/pull/53#issuecomment-128574958>.
>



-- 
William (http://wstein.org)

**Comment by cloutier** [comment]
My bad, I just saw you wrote the username in the VM description.

Turned out my local apache installation interfered with it. I configured my apache to only bind to 127.0.0.1, but I still suspect it's the reason it's not working. I can't connect with my browser with the ip I configured for VirtualBox, and if I try to ssh it connects to my local computer.

I am going to be extremely busy for the next week or so. When I am going to have a bit of free time I am going to try it on a different computer.

Thanks for all the help!

**Comment by cloutier** [comment]
Nevermind, I did a quick try on a windows host and it works like a charm!

**Pull request merged**
