### PR TITLE
webapp: dealing with file listing problems -- issue #1408

### PR DESCRIPTION
**Pull request by haraldschilly**
the way I did test it, is to reload the whole page while the url contains a full path to a file

### CODE REVIEW

**Comment by williamstein** [comment]
> the way I did test it, is to reload the whole page while the url contains a full path to a file

And...?  What is the expected behavior?  How does this actually test anything?  How do you simulate each of the errors.  

Please give me step by step instructions to test this PR.

**Comment by williamstein** [comment]
I tried:
 - just refresh on a valid directory: works as expected, which I guess tests we didn't break things horribly again
 - refresh on a directory that doesn't exist -- Loading spins "forever" (several minutes), and I give up.  There *should be* an almost immediate error in this case.

**Comment by williamstein** [comment]
I did read all this code and in certainly looks fine.   I'm OK with it being merged.   I just don't know what it is supposed to accomplish exactly or how to test it.

**Comment by haraldschilly** [comment]
hmm, the proper way would be some mocking to trigger a file listing error. and yes, I meant to do this reloading, because that's where the codepath has those changes in it. reloading a non-existing directory should fail, yes, but I have no idea what's going on. I'll have a look.

**Comment by haraldschilly** [comment]
I've pushed 05731ae which (hopefully) addresses that problem of opening a non-existing directory. The tricky detail is, that calling smc-ls works fine even though it returns an error. This "good" error triggers calling the function again (until the timeout of 4 minutes).

**Comment by williamstein** [comment]
Fantastic!

**Pull request merged**
