### PR TITLE
Upgrade jQuery to 2.1.4

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by haraldschilly** [comment]
Has this been tested to not break anything?

**Comment by nikolas** [comment]
No, because the [setup instructions](https://github.com/sagemathinc/smc/blob/master/INSTALL.md) are pretty involved, so I haven't been able to set up my own instance yet.

Maybe something like docker / docker-compose could simplify the setup process for development purposes?

But anyways, going from jQuery 2.0.3 to 2.1.4, I've never seen any compatibility issues. But yeah you will have to test this yourself until I figure out how to set up my instance of smc.

**Comment by williamstein** [comment]
I didn't notice any issues with the upgrade to 2.1.4.

**Comment by williamstein** [comment]
now live on the site.

**Pull request merged**
