### PR TITLE
Issue739python3

### PR DESCRIPTION
**Pull request by DrXyzzy**
Ref: #739 and #740.

- Invoke `anaconda3` jupyter kernel when `%python3` mode is used
- fix ansi highlighting of errors as reported in #739 
- add support for input() for %python3 mode (actually for any mode using either python3 or anaconda3 kernel)
- fix latex output generated by %python3
- `debug` is no longer an optional argument to the `jupyter()` kernel launch function. Instead, set e.g. `python3.jupyter_kernel.debug = True` after starting a kernel and jupyter messages will be sent to sage_server log
- add pytest cases for %python3 - this PR passes all 79 tests

### CODE REVIEW

**Comment by haraldschilly** [comment]
ok, read the code, looks good. the part about detecting plain text vs. latex is odd, but probably the only way to make this work well. what I'm also a bit puzzled about are all those additional `continue` statements. I assume that has something to do with how the protocol actually works. At some point, this should obviously be cleaned up, but let's focus on getting it work well first.

**Comment by haraldschilly** [comment]
testing it in my own dev project reveals, that it works fine and all tests pass.

what's not working is that new input box. initially it looks fine, but then some sort of "hiccup" happens and it duplicates. of course, that could be entirely related to how the output is rendered, but it's not working well. Sometimes, I get it to work initially for a split second, but then it's broken.

smc-python3-jupyter-input-broken

**Comment by DrXyzzy** [comment]
Thank you for the review. The input hiccup is a known problem with sagews `raw_input()`, #358 which is on track to be fixed soon per yesterday's chat.

**Comment by haraldschilly** [comment]
ok, I see, I've merged it

**Pull request merged**
