### PR TITLE
[review requested] sagews pytest2

### PR DESCRIPTION
**Pull request by DrXyzzy**
add tests to pytest suite for sage worksheets, including
- sh mode tests for checking work with #738 
- startup latency for sage_server

no changes to production SMC code, only to pytest suite under `src/smc_sagews/smc_sagews/tests`

### CODE REVIEW

**Comment by haraldschilly** [comment]
nice, I just edited a tiny detail directly here in github

**Comment by haraldschilly** [comment]
hmm, tried it, and got one failing test. I tried it with python -m pytest and sage -python -m pytest ...


```
python -m pytest tests                                                                                                                   09:39:35
========================================================================================== test session starts ==========================================================================================
platform linux2 -- Python 2.7.10, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /projects/14eed217-2d3c-4975-a381-b69edcb40e0e/smc/src/smc_sagews, inifile:
plugins: hypothesis-3.4.2
collected 15 items 
 
tests/test_sagews.py ...F.
tests/test_sagews_modes.py .....
tests/test_sagews_timing.py ...s
tests/test_sagews_x.py .
 
=============================================================================================== FAILURES ================================================================================================
_____________________________________________________________________________________________ test_issue70 ______________________________________________________________________________________________
 
exec2 = <function execfn at 0x7f179c3df578>
 
    def test_issue70(exec2):
        code = dedent(r"""
        for i in range(1):
            pass
        'x'
        """)
        output = dedent(r"""
        'x'
        """).lstrip()
>       exec2(code, output)
 
tests/test_sagews.py:33:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
code = "\nfor i in range(1):\n    pass\n'x'\n", output = "'x'\n", pattern = None
 
    def execfn(code, output = None, pattern = None):
        m = message.execute_code(code = code, id = test_id)
        m['preparse'] = True
        # send block of code to be executed
        sagews.send_json(m)
        # check stdout
        if output or pattern:
            typ, mesg = sagews.recv()
            assert typ == 'json'
            assert mesg['id'] == test_id
>           assert 'stdout' in mesg
E           assert 'stdout' in {'done': False, 'event': 'output', 'id': 4, 'stderr': 'Error in lines 1-3\nTraceback (most recent call last):\n  File "/...\n\', \'\', \'single\') in namespace, locals\n 
 File "<string>", line 3\n    \'x\'\n      ^\nSyntaxError: invalid syntax\n'}
 
tests/conftest.py:347: AssertionError
============================================================================ 1 failed, 13 passed, 1 skipped in 4.15 seconds =============================================================================
```

**Comment by haraldschilly** [comment]
So, uhm, no idea how editing PRs from the command line works? Pushing my branch didn't do anything to yours ... it only worked through the GitHub UI.

Regarding my error above, I had to delete all my local smc_* python libs and restart the sage server in my project, then it worked better. I was probably running some outdated code.

Still, there was one simple  newline issue left ....

**Comment by DrXyzzy** [comment]
Thanks, that test failure looked like a real regression test, looking for a bug that had been reported & fixed. So something was working.

**Comment by haraldschilly** [comment]
oh yes, I thought the whole time that this should be fixed! so indeed, it's doing something useful :+1:

**Comment by DrXyzzy** [comment]
And your test edit of the PR branch through GitHub UI seems to have worked:
https://github.com/sagemathinc/smc/blob/master/src/smc_sagews/smc_sagews/tests/test_sagews_timing.py#L27

**Pull request merged**
