### PR TITLE
Issue/1391

### LINKED ISSUE #1391: internal links in chat/react-markdown (are suddenly) opening in a new browser tab
This seems new -- not sure what is causing this.

### PR DESCRIPTION
**Pull request by haraldschilly**
this fixes #1391 and some extras

* be explicit about when target="_blank"
* support base url for relative images in chat (i.e.  for smc-in-smc)
* fix links in the root directory in markdown in sagews, i.e. when the path is just a `""`, the string concatenation for the href would introduce two `...//...` in the URL. `join` takes care of that.

### CODE REVIEW

**Comment by haraldschilly** [comment]
uhm, no idea why there are suddenly conflicts...

**Comment by williamstein** [comment]
> uhm, no idea why there are suddenly conflicts...

Because I made a quick hotfix (moving two lines around), which were the same thing you did in one of your commits.

**Comment by williamstein** [comment]
I didn't realize you would make this PR so quickly.

**Comment by williamstein** [comment]
LGTM -- pushed to master.

**Pull request merged**
