### PR TITLE
don't show line number if line = 1 in users viewing document

### PR DESCRIPTION
**Pull request by timothyclemansinsea**
This would address editors like chat where line numbers make no sense

### CODE REVIEW

**Comment by williamstein** [comment]
(sorry if my review sounds harsh -- your actual code here was nice code; it's just not quite the right approach, imho).

**Comment by timothyclemansinsea** [comment]
@williamstein is there already a way to know if a given editor is a codemirror editor? If not is this something that could be easily added after react rewrite? I'd like to do something like `if @props.is_codemirror then @render_line_number`

**Comment by williamstein** [comment]
I think maybe the cursor position for that user would be undefined instead of an actual number (?).  Not sure...

**Comment by timothyclemansinsea** [comment]
@williamstein prior there was `if @props.line`  and yet there was still a line number showing for chat.

**Comment by williamstein** [comment]
It's necessary to understand things more deeply than just looking at `props.line`, e.g., in syncstring.coffee...

**Pull request merged**
