### PR TITLE
Add Student Sorting to Courses

### PR DESCRIPTION
**Pull request by johnjeng**
## Fixes most of #1447  

Things **not** in this PR:
- Custom ordering
- Changing default ordering

### Adds headers to students panel columns
adjusted
Also adjusts some spacing across tabs.

### Spacing on the Assignments tab (Handouts is similar)
assignments

### Settings (and shared project) gets adjusted to match Account Settings
settings

Account settings:
account settings

### Sort without spacing adjustments:
current sort

## Testing
1. Create students in a course
2. Clicking on any of the headers should sort by that column.
3. Clicking on the same header again should reverse the order.
4. Clicking on a different header should start with the arrow pointed down.
5. Any columns not being sorted by should not have any arrow next to the name
6. The arrow should initially appear next to `Last Name`
7. Arrow down should mean a -> z (caps ignored) for names and emails.
8. Arrow down for `Last Active` should mean most recent to never used
9. Arrow down for `Hosting Type` should put members before free servers.

### CODE REVIEW

**Comment by williamstein** [comment]
NICE!

**Comment by haraldschilly** [comment]
There was one support request today, where the course listing didn't load. I don't know if there was an exception, but my vague feeling is that it could be related. The browser was Safari.

**Comment by johnjeng** [comment]
Interesting. Was it fixed?

**Comment by williamstein** [comment]
We can't replicate the problem.  Dima thinks the user just has very slow internet....

**Pull request merged**
