### PR TITLE
add pricing information for student-in-courses to pricing and other pages (or at least a wiki page and a link)

### PR DESCRIPTION
**Pull request by timothyclemansinsea**

### CODE REVIEW

**Comment by GregoryBard** [comment]
I can help write such a page, if I am given the information. This would be
easy for me to do. Can someone link me to the raw data?
---Greg

**Comment by williamstein** [comment]
> I can help write such a page,

I think the content of this PR is it already being done.  Do you agree with the wording?  See https://github.com/sagemathinc/smc/pull/807/files

**Comment by GregoryBard** [comment]
The wording seems fine to me.
---Greg

**Comment by haraldschilly** [comment]
so ok, this seems to be ready to be merged?

**Comment by williamstein** [comment]
I ended up rewriting this to provide useful links, clearer structure, answer questions we really have, etc.

**Pull request merged**
