### PR TITLE
webapp/file listing: add download buttons that also support right-click → copy url

### PR DESCRIPTION
**Pull request by haraldschilly**
This is a simple solution for all issues related to #328 

Note, that it also support right-click and "copy url", since it is in the href of an anchor.

What I haven't done is to think much about the styling (we could add a hover text), nor if this also shows up for public file listing (would it work there?). Still, I like it, it's very minimal and it doesn't add much clutter.

It also definitely conflicts with my recent PR #983 since it moves that raw URL creation into a separate function ... merging is trivial, though.

### CODE REVIEW

**Comment by timothyclemansinsea** [comment]
@haraldschilly I like the simplicity.

**Comment by timothyclemansinsea** [comment]
@haraldschilly one issue I have with this is if say html documents are being forced to download even when go to url in a separate tab

**Comment by haraldschilly** [comment]
Hmm, maybe we should make paths ending in htm and html a special case and not force them to be downloaded? (I.e. just leave the content type as it is or undefined and then it will show up)

**Comment by haraldschilly** [comment]
Ok yes, just checked, handling html pages as not being downloaded makes sense, but this is actually something for #982 and not here -- i.e. right now, without #982, the html page shows up normal in the new tab with this patch.

**Comment by williamstein** [comment]
screen shot 2016-10-04 at 12 10 53 pm

**Pull request merged**
