### PR TITLE
Issue/1506

### PR DESCRIPTION
**Pull request by DrXyzzy**
Ref. #1506 

To review:
1. Install new code in dev mode and run pytest suite.

    ```
    cd [current smc-repo]
    git checkout DrXyzzy:issue/1506 # or equivalent
    cd src/smc_sagews
    pip install --user --upgrade ./
    cd smc_sagews/tests
    python -m pytest # expect all 124 tests to pass
    ```

1. Create sagews file and do %octave plot. Verify plot size is correct, e.g.

    ```
    %octave
    x = -10:0.1:10;
    plot (x, sin(x));
    ```

### CODE REVIEW

**Comment by williamstein** [comment]
> Create sagews file and do %octave plot. Verify plot size is correct, e.g.

How do I know what "correct size" is?  I just tried, and to my older eyes, the plot seems pretty small and hard to see (e.g., small labels).  I'm not sure what to expect.

image

**Comment by haraldschilly** [comment]
from my experience, octave plots always have a very small font size

**Comment by haraldschilly** [comment]
well, I give this a positive review. looks sensible and all tests pass. 

(although, on first try it had a timeout, so I'm wondering if there are "soft errors" (aka "warnings"?) instead of such hard errors. my thought is, that it did load, but just took longer than expected. if it still works, it's just something we wouldn't desire but it's not really broken. e.g. I was running the tests while restarting my dev project and octave in there, so it's sensible to take longer than in a perfect situation)

**Comment by DrXyzzy** [comment]
About "correct size", I should have indicated that the goal for this PR was maintaining the same resolution as the jupyter notebook running octave, which gives plot resolution as 560x420. The present PR achieves that.

**Pull request merged**
