### PR TITLE
show_identifiers() #63

### PR DESCRIPTION
**Pull request by DrXyzzy**
Reference: #63 

Fix was tricky because
- I was only able to set sage.misc.session.state_at_init after first code block has executed
- sage.misc.session.init() is not called until first invocation of show_identifiers()
- need to set sage.misc.session.state_at_init before first user cell executes or risk missing variable assignments in that cell
- worksheet server adds 'smc', 'salvus', 'require', and sometimes other identifiers to session namespace - I made the requirements choice of removing these before returning show_identifiers() because user can't shadow them anyway.

Pytest cases have been added for show_identifiers(), reset(), save_session(), load_session(). To run just the new tests:
```
cd ~/smc/src/smc_sagews/smc_sagews/tests
python -m pytest test_sagews.py::TestIdentifiers
```

### CODE REVIEW

**Comment by williamstein** [comment]
I wanted to just give this a positive review (for your birthday) but quickly found a bug. Try doing
```
sage = 1
show_identifiers()
```
This fails because `show_identifiers()` uses eval...

I think it would be better to just copy over the source of show_identifiers from `sage.misc.session.show_identifiers` rather than doing `eval('sage.misc.session.show_identifiers()',salvus.namespace)`, due to these subtle issues.

Also, I wrote `sage.misc.session.show_identifiers` in the first place, and if you look you'll see it's about 3 lines of code total, including functions it calls... 

Here's the original function it was based on: https://magma.maths.usyd.edu.au/magma/handbook/text/51#429

**Comment by DrXyzzy** [comment]
Setting `sage`. I didn't see that coming. Yet not using `eval()` somehow pulled in the wrong context for `show_identifiers()`, even with salvus namespace. I puzzled over that for more hours than I want to admit.

Reimplement it is.

**Comment by DrXyzzy** [comment]
This workaround - b59b339 - came to me, uninvited. I added a test case for assigning to `sage`, too. Still want the rewrite?

**Comment by williamstein** [comment]
> Still want the rewrite?

I'll merge this, but let's consider it technical debt, since I don't like these eval, which make me nervous.  But this is a solid workaround, and there are many other important BUGS to squash!

**Pull request merged**
