### PR TITLE
For #1493: add start/stop student projects to assignments panel

### PR DESCRIPTION
**Pull request by timothyclemansinsea**
image

For #1493

### CODE REVIEW

**Comment by williamstein** [comment]
It looks like you took up half the screen with a nice big panel that will get rarely used.    I'm worried.  I was imaging something more subtle, e.g., a little button on the far right (or to the left of "add assignments"), labeled "Projects..." (?).  When clicked, then your panel would appear. 

@johnjeng what do you think?

**Comment by johnjeng** [comment]
Closing this. I think it should be integrated into the student's panel and maybe a column which says if the project is running or not.

**Comment by timothyclemansinsea** [comment]
@johnjeng I don't understand why you think this should be on the students panel when #1493 is specifically for speeding up grading which is not handled in the students panel. Please explain. For now I'm fixing this PR by doing what @williamstein suggests.

**Comment by timothyclemansinsea** [comment]
image
image

**Comment by johnjeng** [comment]
>specifically for speeding up grading

Sorry, my brain hadn't switched contexts from the student panel that I've been working on. 

Making start all student projects more robust is going to be next on my todo list.

**Pull request closed without merging**
